site_name: Koki Short
pages:
 - Home: index.md
 - User Guide:
   - Getting Started: user-guide/index.md
   - Command Line: user-guide/command-line.md
   - Getting Help: user-guide/getting-help.md
   - Best Practices: user-guide/best-practices.md
 - Resources: 
   - Introduction: resources/index.md
   - Pod: resources/pod.md
   - Service: resources/service.md
   - Deployment: resources/deployment.md
   - ReplicaSet: resources/replica-set.md
   - ReplicationController: resources/replication-controller.md
   - Job: resources/job.md
   - DaemonSet: resources/daemon-set.md
 - Modules:
   - Introduction: modules/index.md
theme: readthedocs
